# issue_prefix: "" # Optional prefix for new issues
# tracker_path: # Optional path to the issue tracker if you want to store the issues in a different location

# status_list: open, backlog, planned, in_progress, review, duplicated, closed, canceled
# resolved_status_list: closed, canceled, duplicated
# priority_list: urgent, high, *medium, low

# issue_branch_name_template: "<%%= issue_folder_name %%>"
# Example: "pr/<%%= issue_folder_name %%>-dev"

# scripts:
#   - name: "Open Primary Issue"
#     description: "Opens the first selected issue in Vim" # Optional, nullable
#     command: "vim"
#     args:
#       - "$MUD_ISSUE_ID"
