name: Test and Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --runInBand --logHeapUsage 

      - name: Build
        run: npm run build

      - name: dist
        run: npm run dist

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mud-binary
          path: |
            package.json
            publish
            README.md
